baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Help Missing'

[params]
  description = "A directory of missing persons databases and organizations worldwide"
  author = "Help Missing"

[markup.goldmark.renderer]
  unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Countries"
  url = "/countries/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Coverage Map"
  url = "/statistics/"
  weight = 4

[[menu.main]]
  name = "Social Feed"
  url = "/social-feed/"
  weight = 5
